name: Setup DockerEdition

on:
  workflow_dispatch:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up variables
      id: vars
      run: |
          echo "app_version=$(python3 -c 'from version import __version__ as v; print(v)')" >> "${GITHUB_OUTPUT}"
          echo "sha_short=$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"

    - name: Append git revision to project version
      run: |
          sed -ri "s/^__version__\s*=\s*\"[^\"]+/\0.${{steps.vars.outputs.sha_short}}/" version.py

    - name: Install system dependencies
      run: |
          sudo apt update
          sudo apt install libgirepository1.0-dev python3-testresources

    - name: Download AppImage Builder
      run: |
          curl -L https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage -o appimage-builder
          chmod +x appimage-builder

    - name: Create AppImage
      env:
          APPIMAGE_EXTRACT_AND_RUN: 1
          APP_VERSION: ${{steps.vars.outputs.app_version}}.${{steps.vars.outputs.sha_short}}
          PYTHON_VERSION: ${{env.PYTHON_VERSION}}
      run: |
          ./appimage-builder --recipe appimage/AppImageBuilder.yml

    - name: Create release folder
      run: |
          folder='Twitch Drops Miner'
          mkdir "${folder}"
          cp *.AppImage manual.txt "${folder}"
          7z a Twitch.Drops.Miner.Linux.AppImage.zip "${folder}"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
          if-no-files-found: error
          name: Twitch.Drops.Miner.Linux.AppImage
          path: Twitch.Drops.Miner.Linux.AppImage.zip
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t Twitch_Drops_Miner_Docker_Supported:latest .

    

    
  
