name: Setup DockerEdition

on:
  workflow_dispatch:
  push:
    branches:
      -main

env:
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t twitch_drops_miner_docker_supported:latest .

    - name: Save Docker image to file
      run: |
        docker save -o twitch_drops_miner_docker_supported_latest.tar twitch_drops_miner_docker_supported:latest

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: twitch_drops_miner_docker_supported_latest
        path: twitch_drops_miner_docker_supported_latest.tar
        retention-days: 30  # 将保留天数设置为 1 天 最多可设置90天
 
  update_releases_page:
    name: Upload builds to Releases
    if: github.event_name != 'pull_request'
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set up variables
        id: vars
        run: |
          echo "date_now=$(date --rfc-3339=seconds)" >> "${GITHUB_OUTPUT}"

      - name: Download build artifacts from previous jobs
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload builds to Releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: artifacts/*/*
          body: |
            **Build from https://github.com/DevilXD/TwitchDropsMiner/tree/master**

            - Last build date: `${{steps.vars.outputs.date_now}}`
            - Reference commit: ${{github.sha}}
          name: Development build
          prerelease: true
          removeArtifacts: true
          tag: dev-build

    

    
  
