name: Setup DockerEdition

on:
  workflow_dispatch:
  push:
    branches:
      -main

env:
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t twitch_drops_miner_docker_supported:latest .

    - name: Save Docker image to file
      run: |
        docker save -o twitch_drops_miner_docker_supported_latest.tar twitch_drops_miner_docker_supported:latest

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images
        path: twitch_drops_miner_docker_supported.tar
        retention-days: 30  # 将保留天数设置为 1 天 最多可设置90天

    

    
  
